"""Type stubs for the Rust extension module."""

import os
from collections.abc import Iterator
from typing import IO

__version__: str

class Presentation:
    @staticmethod
    def from_bytes(data: bytes) -> Presentation: ...
    @staticmethod
    def from_path(path: str) -> Presentation: ...
    @property
    def slides(self) -> Slides: ...
    @property
    def slide_width(self) -> int | None: ...
    @property
    def slide_height(self) -> int | None: ...
    def save(self, target: str | os.PathLike[str] | IO[bytes]) -> None: ...

class Slides:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Slide: ...
    def __iter__(self) -> Iterator[Slide]: ...

class Slide:
    @property
    def slide_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def shapes(self) -> SlideShapes: ...

class SlideShapes:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Shape: ...
    def __iter__(self) -> Iterator[Shape]: ...
    def add_textbox(self, left: int, top: int, width: int, height: int) -> Shape: ...

class Shape:
    @property
    def shape_id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def has_text_frame(self) -> bool: ...
    @property
    def text_frame(self) -> TextFrame: ...
    text: str
    left: int | None
    top: int | None
    width: int | None
    height: int | None

class TextFrame:
    @property
    def paragraphs(self) -> list[_Paragraph]: ...
    text: str
    def add_paragraph(self) -> _Paragraph: ...

class _Paragraph:
    @property
    def runs(self) -> list[_Run]: ...
    text: str
    def add_run(self) -> _Run: ...

class _Run:
    text: str
